New page controller
ElectronicCats/Rover pull request #4
Opened 2020-02-11 19:20 UTC by Oscar-Raygoza

2020-02-11 20:47 UTC, Oscar-Raygoza commented
testeado y funcionando

2020-02-11 20:54 UTC, sabas1080 requested changes

2020-02-11 20:54 UTC, sabas1080 commented on Firmware/Cat_Finder/app_httpd.cpp
> +//Actualiza datos cada 3 seegundos
Corregir Typo

2020-02-11 20:54 UTC, sabas1080 commented on Firmware/Cat_Finder/app_httpd.cpp
> +  //Actualiza datos cada 3 seegundos
Corregir Typo

2020-02-12 00:44 UTC, sabas1080 approved these changes

2020-02-12 01:10 UTC, merged